# Site settings
title: "kieslee's blog"
username: "kieslee"
email: "lleelm@gmail.com"
url: "http://kiesleeã€‚github.io"

# Build settings
# markdown: kramdown
markdown: redcarpet
# pygments: true
highlighter: pygments
permalink: pretty
